version: "3"
services:
  chrome-1:
    container_name: chrome-1
    image: selenium/node-chrome:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NO_VNC_PORT=7900
    ports:
      - "7900:7900"
  chrome-2:
    container_name: chrome-2
    image: selenium/node-chrome:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NO_VNC_PORT=7902
    ports:
      - "7902:7902"

  edge-1:
    image: selenium/node-edge:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NO_VNC_PORT=8000
    ports:
      - "8000:8000"
  edge-2:
    image: selenium/node-edge:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NO_VNC_PORT=8002
    ports:
      - "8002:8002"

  firefox-1:
    image: selenium/node-firefox:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NO_VNC_PORT=8100
    ports:
      - "8100:8100"
  firefox-2:
    image: selenium/node-firefox:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NO_VNC_PORT=8102
    ports:
      - "8102:8102"

  selenium-hub:
    image: selenium/hub:4.9.1-20230508
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"